-- +migrate Up
CREATE TABLE clients
(
id INTEGER PRIMARY KEY,
nickname VARCHAR(255) NOT NULL,
realname VARCHAR(255) NOT NULL,
password VARCHAR(255),
host VARCHAR(255) NOT NULL,
port INTEGER NOT NULL DEFAULT 6667,
ssl INTEGER(1) NOT NULL DEFAULT 0,
created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

-- +migrate Down
DROP TABLE clients;
